#!/bin/sh

if [ "$(mpc status | grep playing)" == "" ]; then
	MPC="\x04  "
else
	MPC="\x06 $(mpc status --format "  %artist% - %title% ("$(mpc status | sed -n 2p | awk -F" " '{ print $3 }')")" | head -1)"
fi

DATE="$(date +"  %a"\ "%d"\ "%h "\|\ \ "  %H":"%M")"

BATTERY="  $(cat /sys/class/power_supply/BAT0/capacity)% "

if [ "$(amixer get Master | awk -F'[][]' 'END{ print $6 }')" == "off" ]; then
	VOLUME="x $(amixer get Master | awk -F'[][]' 'END{ print $2 }')"
else
	VOLUME="  $(amixer get Master | awk -F'[][]' 'END{ print $2 }')"
fi

CPU="  $(top -b -n1 | grep "Cpu(s)" | awk '{print $2 + $4}')%"

RAM="  $(free -m | awk 'NR==2{printf "%s/%sMB\n", $3,$2 }')"

echo -e "\x01 $MPC \x01 \x03 $RAM \x01 \x04 $CPU \x01 \x03 $VOLUME \x01 \x02 $DATE \x01 \x03 $BATTERY\x01"
